'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/Provider";
import Navbar from "@/components/Navbar/Navbar";
import { usePathname } from "next/navigation";
import { Bounce, ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Hide navbar on these routes
  const hideNavbarRoutes = ["/login", "/signup", "/forgotpassword"];
  const shouldHideNavbar = hideNavbarRoutes.includes(pathname || "");
  return (
    <html className="h-full bg-gray-100" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gray-100`}
        data-new-gr-c-s-check-loaded="14.1232.0"
        data-gr-ext-installed=""
      >
        <Providers>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
          />
          {!shouldHideNavbar && <Navbar>
          {children}          
          </Navbar>}
          {shouldHideNavbar && children}
        </Providers>
      </body>
    </html>
  );
}
